# Generated by Django 5.1 on 2024-08-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.IntegerField(max_length=2)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
